### ISSUE TITLE
Security trouble

### ISSUE THREAD

**Issue by GFdevelop** [jonhoo/hasmail#10]
Really you print the password at line 48 in `connect.go`?!?!?

`fmt.Printf("login %s '%s' '%s'\n", address, username, password)`

Why?

**Comment by jonhoo** [comment]
Because it was handy while setting up my account during development :) I've removed it now though -- thanks for the heads up! You may also want to try [buzz](https://github.com/jonhoo/buzz) instead, since that's more actively maintained.
