### ISSUE TITLE
Can hardly distinguish icon variations - how to change them?

### ISSUE THREAD

**Issue by wSzki** [jonhoo/hasmail#13]
Hello, 
Thanks for this tool ! been looking for something like this for a while.

I have an issue with the tray icons; i can hardly distinguish the variations. 

Is there a way to change them? 
I've checked the source code but i don't understand where the icons are coming from

Thanks

**Comment by jonhoo** [comment]
Ah, I basically don't maintain the Go implementation of this any more. The new implementation (in Rust) lives in https://github.com/jonhoo/buzz/, which should hopefully be easier to customize and understand :+1:
